#!/usr/bin/env bash
# Generates a 4-validator QBFT network (genesis + node keys) and a docker-compose file.
# Idempotent: skips generation if networkFiles already exists.
set -euo pipefail
cd "$(dirname "$0")"
IMG=hyperledger/besu:latest
if [ ! -d networkFiles ]; then
  docker run --rm -v "$PWD:/data" $IMG operator generate-blockchain-config \
    --config-file=/data/qbftConfigFile.json --to=/data/networkFiles --private-key-file-name=key
fi
i=1
for d in networkFiles/keys/0x*; do
  rm -rf node$i; mkdir -p node$i
  cp "$d/key" "$d/key.pub" node$i/
  i=$((i+1))
done
PUB1=$(cat node1/key.pub | sed 's/^0x//')
cat > docker-compose.yml <<YML
# Tandur local ledger: 4 QBFT validators (ministry, operator, auditor, bank) + Postgres for the operator.
# Generated by setup.sh. Chain ID 6221. Zero gas price (enterprise profile).
name: tandur
networks:
  tandur:
    driver: bridge
    ipam:
      config:
        - subnet: 172.28.0.0/24
x-besu: &besu
  image: $IMG
  restart: unless-stopped
  user: "0"
  networks: [tandur]
  environment:
    BESU_LOGGING: INFO
volumes:
  pg: {}
  node1: {}
  node2: {}
  node3: {}
  node4: {}
services:
YML
for n in 1 2 3 4; do
  ip="172.28.0.1$n"
  rpcport=$((8544+n))
  wsport=$((8644+n))
  case $n in 1) label=ministry;; 2) label=operator;; 3) label=auditor;; 4) label=bank;; esac
  cat >> docker-compose.yml <<YML
  validator$n:
    <<: *besu
    container_name: tandur-validator-$label
    volumes:
      - ./networkFiles/genesis.json:/config/genesis.json:ro
      - ./node$n/key:/config/key:ro
      - node$n:/data
    ports:
      - "$rpcport:8545"
      - "$wsport:8546"
    command: >
      --data-path=/data
      --genesis-file=/config/genesis.json
      --node-private-key-file=/config/key
      --profile=ENTERPRISE
      --min-gas-price=0
      --p2p-host=$ip
      --p2p-port=30303
      --bootnodes=enode://$PUB1@172.28.0.11:30303
      --rpc-http-enabled --rpc-http-host=0.0.0.0 --rpc-http-port=8545
      --rpc-http-api=ETH,NET,WEB3,QBFT,TXPOOL,ADMIN,DEBUG
      --rpc-http-cors-origins=*
      --rpc-ws-enabled --rpc-ws-host=0.0.0.0 --rpc-ws-port=8546
      --rpc-ws-api=ETH,NET,WEB3,QBFT
      --host-allowlist=*
      --discovery-enabled=true
    networks:
      tandur:
        ipv4_address: $ip
YML
done
cat >> docker-compose.yml <<'YML'
  postgres:
    image: postgres:16-alpine
    container_name: tandur-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: tandur
      POSTGRES_PASSWORD: tandur
      POSTGRES_DB: tandur
    ports:
      - "5442:5432"
    volumes:
      - pg:/var/lib/postgresql/data
    networks: [tandur]
YML
echo "setup complete: $(ls -d node* | wc -l | tr -d ' ') validator key dirs, bootnode pub ${PUB1:0:16}..."
